version: '2'

services:

  meanjs:
    build: .
    links:
    - mongodb
    depends_on:
    - mongodb
    ports:
    - "3000:3000"
    environment: 
      NODE_ENV: development

  mongodb:
    image: mongo
    #volumes:
    #- ./mongodb:/data/db

  restheart:
    image: softinstigate/restheart
    ports:
    - "8081:8081"
    volumes:
    - ./restheart/docker:/opt/restheart/etc
    - ./restheart/app:/opt/restheart/app
    links:
    - mongodb
    depends_on:
    - mongodb


# curl -u admin:changeit -i -X PUT http://127.0.0.1:8081/data/blog -H "Content-Type: application/json"
# curl -u admin:changeit -i -X PUT http://127.0.0.1:8081/data/blog/posts -H "Content-Type: application/json"    